# Dockerfile for Rask
#   https://github.com/nomlab/rask
#
# Warning: This file is only for used by scripts/setup-docker.sh
#          Do not create image from this Dockerfile manually

FROM ruby:3.0.0

ARG UID

ENV DEBIAN_FRONTEND noninteractive

# Install required packages
RUN curl https://deb.nodesource.com/setup_12.x | bash
RUN curl https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq \
    && apt-get install -y locales sudo build-essential git-core vim libsqlite3-dev nodejs yarn \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN yarn add jquery
RUN yarn add jquery-textcomplete

# Set locale
RUN locale-gen ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_TIME C
ENV TZ Asia/Tokyo
RUN localedef -f UTF-8 -i ja_JP ja_JP.utf8

# Add rask user
RUN useradd -s /bin/bash -u $UID rask
RUN usermod -aG sudo rask
RUN sed -i 's/^%sudo.*$/%sudo ALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers

# Copy app files from cwd
RUN mkdir /home/rask
WORKDIR /home/rask
COPY . /home/rask

RUN chown -R rask:rask /home/rask

# Switch user to jay
USER rask

# Install gem
RUN bundle config set path 'vendor/bundle'
RUN bundle install
RUN bundle exec rails webpacker:install
RUN bundle exec rails tailwindcss:install

# set cmd
CMD ["./scripts/docker/docker-entrypoint.sh"]
